### ISSUE TITLE
Pantheon Autopilot Integration (Visual Regression Testing)

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#104]
Many BADcampers suggested Equalify integrate with [Autopilot](https://pantheon.io/autopilot). Autopilot is used for visual regression testing, previewing changes after Drupal/WP updates. I wonder.. _can Autopilot preview changes related to Equalify's WCAG compliance tools?_ 

Visual regression becomes vital as Equalify goes from testing to updating code (see #69). Theoretically, Equalify could send all the code changes to Pantheon. Autopilot then works its magic, previewing the changes that keep sites WCAG compliant.

Related questions that I hope this ticket eventually answers:
- How can we support visual regression for screen readers?
- What Terminus actions will Autopilot support? Or how do we integrate with Autopilot?
- Is Pantheon even interested in integrating Autopilot with Equalify?

**Comment by kreynen** [comment]
I'm going to use a lot of Pantheon-specific terminologies here to basically say, we'd be unlikely to use Equalify this way.

Most higher ed organizations using Pantheon leverage a [Custom Upstream](https://pantheon.io/docs/guides/custom-upstream).

https://github.com/cu-uis/cu-starterkit-project/wiki/Development:Upstreams is already outdated since we've moved from using a private, on-prem Gitlab instance in combination with GitHub to trusting [GitLab.com](https://gitlab.com/universityofcolorado/), but the codeflow is essentially the same. Currently, Autopilot can't be triggered to run by another service through Terminus, so we reversed our normal process to embrace this. 

We let Autopilot do its thing and look for changes in the Custom Upstreams or project dependencies and then use a Pull Mirror from the dev instance on Pantheon to merge those changes into GitLab where additional testing can be run. We only run additional testing if the VRT passes automatically or after a failure is approved by a site's owner/stakeholders.

In some cases, sites require custom themes, but we try to include enough theme variations in the Upstream that even custom themes are rarely necessary. The goal is that most sites have no custom code because custom, site-specific code is harder to maintain. 

While it would be great to have an Equalify tolerance similar to Autopilot tolerance for visual differences as a deployment gate, I don't understand how Equalify would figure out where a PR/MR would need to be made once you've added an Upstream to the mix.

In our development environment, we would likely only run Equalify on a "canary" site we use to test the Upstream that is repopulated with demo content/urls as part of the functional testing. The real value for us isn't having Equalify being able to create a PR/MR, but simply getting the results of the integrated testing into a consumable "score". 

The way Equalify and Autopilot would interact would be when something is flagged on multiple sites that needs to be addressed at the Upstream level. Merging a fix into the Upstream would result in Autopilot rerunning the VRT. The site owner is really using Autopilot to confirm that the Upstream fix didn't cause a visual regression.

**Comment by bbertucc** [comment]
> most sites have no custom code because custom, site-specific code is harder to maintain.

I've seen that in every Higher Ed team I've worked with. Additionally, most WCAG compliance errors I'm seeing are around user-generated content (missing alt tags, etc). There's little need for visual regression testing with those types of errors.

Closing this issue until someone has a good use case for visual regression. Those interested in the automated fixes aspect of the issue can see #69.
