### ISSUE TITLE
Unable to add a site

### ISSUE THREAD

**Issue by NicolaSaunders** [bbertucc/equalify#123]
When trying to add a new WordPress site for scanning, I am directed to an error page with the following message:

```This page isn’t working service.equalify.app is currently unable to handle this request. HTTP ERROR 500```

I am on MacOS Monterey using Chrome Version 107.0.5304.87 (Official Build) (arm64)

**Comment by bbertucc** [comment]
Hey @NicolaSaunders,

What URL are you trying to add?

Thanks!

**Comment by NicolaSaunders** [comment]
I was trying to add https://www.studio24.net/

**Comment by bbertucc** [comment]
Hey @NicolaSaunders - 

That site blocks public access to its WordPress API, so Equalify can't grab its pages. (You can see the error [here](https://www.studio24.net/wp-json/wp/v2/pages?per_page=100).)

You can try to enable the WP REST API and try again.

Alternatively, I see that you have various Yoast XML sitemaps. You can add a XML sitemap to Equalify instead of the WP URL. IE- Try adding this `https://www.studio24.net/page-sitemap.xml` with "XML Sitemap" selected on the site adder.

PS- Thanks for the great bug report! I created #125, so that users won't have the same issue again.
