### ISSUE TITLE
How can Equalify be sustained?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#131]
Money arouses complex emotions, so I've avoided bringing it up in Equalify conversations. But there comes a time in every open source project's life when the "$" needs to come out, so let's talk money..

To start, I want to say that getting rich is not my goal for Equalify. I aim to make the web more accessible through better automated accessibility testing. This project is designed to inspire better tools that I and others build. That's not to say we're only building Equalify tools. [WAVE](https://wave.webaim.org/) and [axe-core](https://github.com/dequelabs/axe-core) are great tools that I hope we push to be better. I will only actually code something when a solution doesn't exist (ie- crawling and testing thousands of pages, the main function of Equalify).

**To establish a budget for 2023, maybe we can look at data in 2022..**

Digital Ocean charges me $55-105/mo for managed hosting of a database and two servers. I'll probably need to pay them a bit more when the [axe-core web service](https://github.com/bbertucc/axe-equalify) is up. I also paid WAVE $335 for users to use their API, but I think that cost will end when axe-core is integrated. Additionally, I would love to scale up the Equalify [bug bounties](https://bbertucc.notion.site/Bug-Bounties-37cb0c61fb2d4bb984a78cc6e4b4aa56). I gave away $699.55 in 2022, and think it's a fun way to push work forward.

As far as my time is concerned, I have no idea how to value my time. I can say that my personal 2023 budget is around $55k/yr for living expenses and savings. My best work comes when I devote myself full-time to a project, so I hope most of my cash comes from Equalify in 2023.

Considering all that, I guess I would like to raise >$56k in 2023? Does that sound right?

**Now.. to the question of how to raise the money..**

To fund the Equalify work (my own and others'), I'm either thinking about going a donation or paywalled route.

If we went a paywall route, [equalify.app](https://equalify.app) would cost $x/x alerts per month to use. We have 33 users using the service now. Based on current activity, I could see around 11 of the 33 users paying for Equalify.

**What should we charge paying users?**

I like multiples of 11, so perhaps we charge $11/mo to start. That's $121/mo for 11 users. I imagine those initial 11 users would scale up every month I did the work. We get about 6 new users a month, and I bet 2 of those users will pay. So that's $121 this month, $143 next month, .. yielding $2904 in 2023. _Way shy of the $56k goal!_

**How about a donation route?**

If went a donation route, I would go after sponsors to sustain the brunt of the cost then ask anyone who uses [equalify.app](https://equalify.app) for a suggested donation based on the number of alerts they have. 

Pantheon generously gave me $20k in 2023. Various [transactions](https://github.com/bbertucc/equalify/files/10115304/transactions-edupack-to-nov292022.csv) led to a current balance of $4,727.40. I hope to put that money toward 2023's budget.

The folks at Pantheon suggested they would sponsor another year, but I really don't know if they will? Let's just say they do... $20k in the bank! Perhaps I'll go after a few more sponsors - I have some connection with Platform.sh, Github, GitLab, and Automattic. Could we get $40k in sponsorship???

If we got $40k in sponsorship, that would leave only $16k to reach my goal. That $16k could come in asking [equalify.app](https://equalify.app) users for donations. We need to suggest around $77/mo based on the math above to reach $16k. 

**Would people donate $77/mo to use Equalify? Sounds like too much to me. What should we do?**

I want to go the donation route when comparing the paywall and donation route. Relying on donations means the folks who didn't have enough cash to pay for Equalify could get the service for free. That also builds a culture of open source, community-supported, creation.

**What do you think?**

----
EDIT: Adding the [Beta 1 Milestone](https://github.com/bbertucc/equalify/milestones) to this. Since Beta 1 represents a solution that we can grow our userbase on, I would love to have this question figured out by the time we reach Beta 1 (currently scheduled for 1/11/23).

**Comment by bbertucc** [comment]
One person suggested three tier pricing ($11,$33,$1111) and “enterprise” pricing for S,M,L and XL companies.

**Comment by mgifford** [comment]
I think having multiple types of membership is useful. There are several open source projects that are raising a reasonable amount of $$ through either Patreon or even better with https://opencollective.com

The big users for this though are going to be institutions.  For an educational institution, it might be easier to write you a cheque for $5k for knowledge that you will maintain their data and crawl their site for a year. 

There may also be people you want to give access to, because they have agreed to contribute in other ways to the project. 

You also may want to suggest that rather than a donation from the corporations you mentioned, you come to an arrangement where they become your sales team.  If you can demonstrate the value of this product, they should be able to build an easy service that allows them to sell an instance to one of their existing clients for $15k and give you $10k to maintain it. They might want to also just have a console that allows them to set up sites and monitor usage.

You should be thinking of being paid for your time, paying for the infrastructure, and maybe even paying other people on contract to do the things you're not great at. Don't think too small. You might need to be able to scale this up.

**Comment by bbertucc** [comment]
> even better with https://opencollective.com/

Curious of your thoughts around Open Collective, @mgifford .. I have been weighing going with them vs [the software freedom conservancy ](https://sfconservancy.org/)

Great feedback btw! thx!

**Comment by kreynen** [comment]
_> For an educational institution, it might be easier to write you a cheque for $5k for knowledge that you will maintain their data and crawl their site for a year._

Keep in mind that at many large organizations (like the one I work for), it is easier to get a request through purchasing if we are buying a specific license/number of scans, paying for hosting, technical support or even paying membership to be part of an organization than it is to just give $$ to a 501c3 for unspecific, future work. Even when we are hiring contractors, including time to contribute features back to a project in the contract can get flagged. _Why are we paying someone more $$ to give away something we just paid for?_ 

This is a problem many higher ed organizations have trying to contribute to the Drupal Association. DA Organization Level Memberships come with benefits like premium booth placement at DrupalCon that just don't make any sense for universities. Open source software is not something most higher ed purchasing departments really understand and we end up trying to answer questions like... if this software is free, why are we paying for it?  To be fair, the people in purchasing are also managing millions of dollars in Oracle, Microsoft, Salesforce, Adobe, etc licensing. Look at the requests from their perspective, it really doesn't make sense.

I am one of [66 people sponsoring Randy Fay's work on DDEV](https://github.com/sponsors/rfay#sponsors). My employer is happy to license Adobe Create Cloud for me, but I contribute to DDEV personally because it's just too complicated to push this request through purchasing.

$1K for a conference? No problem.
$25 to help support a free camp? It can be done, but it's a hassle. 

https://www.jrockowitz.com/ has written a lot about the challenges in funding high-quality open source. I did a presentation at Stanford's WebCamp last year about how the University of Colorado was able to save $$$ moving from FromStack to Webform, but what do you think happened when I asked about giving a % of what saved eliminating Formstack to support Webform? 

There so many ways you can go with this. None of them are sure things. 

One option would be to combine the governance of the project with membership/funding. This is a big ask for a new project and there's no guarantee it will work... or last if members are seeing features/fixes they want.

**Comment by bbertucc** [comment]
I added a [equalify.app sponsor page](https://equalify.app/sponsor/) and launched [addition sponsorship on GitHub](https://github.com/sponsors/bbertucc). I'll reach out to folks who previously sponsored us (Pantheon + LittleForest). If I can't get enough sponsorship by 12/31, I'll pivot to creating some institutional packages as suggested.

Happy to take anyone's good ideas into account! Thanks y'all!

**Comment by joelhsmith** [comment]
RE: Subscription option - Where I work, they prefer us to pay a single flat rate once a year for a product, rather than an ongoing monthly subscription. They want to buy something tangible and have one receipt. Getting them to agree to recurring payments is a hassle. Although that would need to be an option for some people. Sometimes companies and edu have a certain price point where they have their own authority to make a purchase without as many hoops to jump through. Keeping it under $2k would be key to allow people to make purchases without as much oversight.

Re: Membership option - Where I work, it is hard to get a membership to something because allowing one person to be a member of a group can be viewed as favoritism over other employees who do not get to be members of something. The path of least resistance where I work is a a straight up purchase of a product with one receipt.

Just as a frame of reference... Using Site Improve with an unlimited license is over $85k. A lot of companies pay that kind of money. Eventually, if this product can get to even 70% parity with Site Improve features, it could command a very high price point. Although I know that making a pile of money is not the stated goal of this project.

**Comment by bbertucc** [comment]
Some updates in thinking... 

#177 could be a good avenue. That said, charging for features that large companies might be a more fair way to keep Equalify free for users that don't have as much cash.

Also, I'm very interested in how Equalify can use any cash we receive to support open-source accessibility projects. I know it's super hard to make money on an open-source project, especially when you don't have the business background I have. Perhaps we give x% of revenue to Open Source projects that Equalify uses? I love how [DDEV gives 10%](https://github.com/sponsors/rfay) of sponsorship to projects they use. Maybe we can give 11%?

**Comment by mgifford** [comment]
It is good to be thinking about this in a general sense. Particularly if you want it to be part of a sales/outreach initiative. 

Just don't worry too much about how you are going to disperse the cash you don't yet have. It is good at this stage to talk about being inspired by these other projects. But focus on what clients are willing to pay for now. 

I expect that 90% of them won't care much about the 10% sponsorship (or whatever you come up with). It will be a nice feel-good, but it probably won't drive sales.

**Comment by bbertucc** [comment]
> Just don't worry too much about how you are going to disperse the cash you don't yet have.

Gotta keep that in mind for sure!

**Comment by bbertucc** [comment]
> I expect that 90% of them won't care much about the 10% sponsorship (or whatever you come up with). It will be a nice feel-good, but it probably won't drive sales.

Driving goodwill amongst open-source creators is my main goal. Most folks are attracted to Equalify because it's open-source. I want to leverage as many open-source tools as possible and believe OS creators should get a cut.

**Comment by mgifford** [comment]
Being open source is rarely an incentive for most potential customers. They might think it's a good idea, but the folks with the customers need to know:
- It works as well or better than anything else
- that it will help them reduce risks within their organization
- it may give them the ability to innovate and customize the reporting to help support their team.  

People with the purse strings see open source = free.  Least most of the time.

**Comment by bbertucc** [comment]
The users I've surveyed are into investing in open source. Their hesitation is that Equalify doesn't have the features (yet) of accessibility platforms they use. Another holdup is complicated procurement procedures. Many of these users work for Higher Ed and government agencies that require complex qualifications like VPATs. 

I bet that folks will work with us if we can make an open-source platform with tools just as good as any competitor. The bonus will be when we inspire open-source creators to integrate new features with Equalify.

**Comment by kreynen** [comment]
I agree with @mgifford about "open source is rarely an incentive for most potential customers" when it comes to the top-level IT leadership, but solutions like this are often brought to those decision-makers/purchase order approvers by someone people who DO care about the license of a project. In our use case, the teams managing a large number of Drupal sites want something more flexible than the commercial services that can be integrated with our editing experience. We've already experienced working with closed-source, commercial solutions. We'd rather have something we can customize.

At least in my corner of higher ed, we're beyond the open source = free thinking and have moved on to open source = flexibility + costs in forms other than licenses. In the case of Drupal, the cost becomes the internal development teams who have to figure out issues with the help of a community with no 1-800 number of call.

**Comment by bbertucc** [comment]
@kreynen @mgifford - Your comments inspired a profound reflection on this issue’s question while looking through data I have on Equalify so far (this is primarily emails people send me and stuff posted on GitHub).

I’ve arrived at two conclusions that I hope speaks to your great insight and other insight on this chain:
1. **There’s no way to get a living wage from Equalify now.** The project's focus should be on features, not sales.
2. **Open Source development is key to Equalify’s success.** Beyond the reasons @kreynen mentioned, I don’t think it’s ethical to safeguard intellectual property for financial gain. I won’t work on Equalify if it isn’t open and if I don’t work on Equalify, who will? 

Also, I still think Equalify can serve a valid purpose. **We need an accessibility platform that has ethics at its heart.** It’s sad to say that that doesn’t exist (please prove me wrong so that I can roll in the grass instead of code all day! 😊)

So here are my decisions to resolve this issue:
1. Don’t worry about cash via Equalify now - it’s just a stress point.
2. Work half-time instead of full-time on Equalify.
3. Spend half of my time on commissioned/sponsored projects. 

I am lucky enough to have some commissioned projects lined up. They give me several months of living expenses and 🤞, someday Equalify generates cash so I can devote my time to building this ethical platform.

As part of the "fingers crossed" policy, I’ll also formally start taking sponsorship for Equalify:

https://github.com/sponsors/bbertucc

The monthly sponsorship levels are for good vibes. The one-time sponsorship level will buy my time so that I can devote more time to this project.

Of course, all this is up for debate. I have added these ideas to [My Ethical Business](https://bbertucc.notion.site/My-Ethical-Business-a55c25006c5c4b53b233df1f5c9df4da) notion page. Last year, after adding my work plan to that page, I kept with it for a year - so there's a pretty good chance I'll keep to the plan.

Closing this issue - for now. feel free to comment! EQUALIFY WILL ALWAYS BE OPEN!

**Comment by bbertucc** [comment]
Reopening this issue. Probably need something in our docs (maybe in [README.md](https://github.com/bbertucc/equalify#readme)) that speaks to the important values expressed here.

Hopefully, this can be done by the ["I Emoji Heart Accessibility"](https://github.com/bbertucc/equalify/milestone/6) release!

**Comment by bbertucc** [comment]
Closing this with [6e52bc3](https://github.com/bbertucc/equalify/commit/6e52bc3674a356ad3f9b1fafd059f0193c1e45ba)

**Comment by bbertucc** [comment]
Merged into [beta-1](https://github.com/bbertucc/equalify/tree/beta-1).

**Comment by bbertucc** [comment]
Reopening issue. On second review, 6e52bc3 updates didn't do anything to resolve this issue. Also changing the title of this issue. The issue is not making money. The issue is sustaining Equalify.

**Comment by bbertucc** [comment]
#202 might be an answer.

**Comment by bbertucc** [comment]
The first draft of this business plan works to resolve this issue: https://github.com/EqualifyApp/handbook/blob/business/Business.md .. Please add any feedback!

**Comment by kreynen** [comment]
I suggested some fixes, but I think you are going to run into issues classifying Ambassadors only as leads helping you sell the software within an organization in higher ed. Salesforce has an MVP program based on contributions to the community that many higher ed groups are involved in, but there are large universities that do not allow staff to participate in Pantheon's Hero program because of the way that program is structured. If you are giving a group benefits to help you sell services, that will often conflict with the policies of large, public institutions.

**Comment by bbertucc** [comment]
Thanks @kreynen. My intention isn't to provide a rewards system, but rather to explain an internal sales process to prioritize employee time. Maybe this is clearer? https://github.com/EqualifyApp/handbook/commit/11505aafdd6a10d078a96917a202ba2689589270

**Comment by bbertucc** [comment]
Closing this issue. As much as I would love ideas to generate a solution, I think we're going to just have to try lots of options until one sticks. Thanks for all your input! Feel free to add more.
