### ISSUE TITLE
How can we avoid including $db with every function that queries the $db?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#15]
I didn't plan on making every $db call a function, but it happened.

Now I have to require `models/db.php` and `$db` every time I want to query the db.

I know that creates lots of redundancy.

Curious if there is a simpler solution?

**Comment by ebertucc** [comment]
Yes: singletons and/or factories.

Creating a singleton class to wrap the database connection lets you initialize the connection once without having to then pass the connection around. [This blog post](https://ugur-muslim.medium.com/singleton-php-bf60c1cde180) has a pretty good breakdown of how this works.

[Dependency injection](https://osmianski.com/2019/08/dependency-injection-in-php.html) is another option if you want to avoid singletons for testing/maintainability purposes, but imo it's 1) overkill if you don't want to support multiple DB engines *at the same time* (the singleton class still abstracts the DB logic from the rest of the app, so you can update in one place if desired later on), and 2) mostly proposed by people who hate on singletons due to cargo cult.

Relevant reddit discussion [here](https://www.reddit.com/r/PHP/comments/dzt7v/is_singleton_ok_for_database/).
```

**Comment by ebertucc** [comment]
Submitted a PR with one way this could look. Lemme know what you think.
