### ISSUE TITLE
Accessible Multi-Select Dropdown

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#210]
## Problem
Automated scanners like axe include lots of tags. When filtering by tags, the UI is cluttered if we simply list all those tags. Yet existing UX solutions, like [Chosen](https://harvesthq.github.io/chosen/), are not accessible.

## Desired Solution
We need an accessible solution that allows a user to search through 20+ tags and select tags. Selected tags should be displayed in a way that clearly shows they are active. Chosen's [example of "multiple select with groups"](https://harvesthq.github.io/chosen/#optgroup-support) demonstrates UX that would work, but it is not an accessible solution. 

## Development Notes
The multi-select would replace the wall of checkboxes on our reports page. I've included a screenshot of that wall below. Relevant code files: 
- https://github.com/bbertucc/equalify/blob/beta-1-rc1/views/report_settings.php
- https://github.com/bbertucc/equalify/blob/beta-1-rc1/theme.css
Anyone jumping on this should remember we we're currently working from the [beta-1-rc1 branch](https://github.com/bbertucc/equalify/tree/beta-1-rc1).

![Screenshot of Equalify's report settings page with a list of over 20 checkboxes that are related to various filters](https://github.com/bbertucc/equalify/assets/46652/a8441d66-d555-48ad-b999-e88b8df993c4)

**Comment by bbertucc** [comment]
I could also see us using this in #204 .. specifically to simplify checkbox areas in the "report settings", wireframed [here](https://miro.com/app/board/uXjVMX3i1XA=/?moveToWidget=3458764558969383015&cot=14).

**Comment by tvararu** [comment]
We built the [GDS accessible autocomplete component](https://github.com/alphagov/accessible-autocomplete) precisely because the [existing solutions were not accessible and they weren't easy enough to work on / improve ourselves](https://github.com/alphagov/accessible-autocomplete#why-another-autocomplete). Tacking on accessibility at the end is really hard.

While it [doesn't support tagging or multi-select out of the box](https://github.com/alphagov/accessible-autocomplete/issues/480), you can use a different pattern; select an item, then click an "Add another" button that reveals a second (or third, or etc...) autocomplete.

**Comment by bbertucc** [comment]
Closing this issue since it's not discribing a specific issue, but we'll definitely look back on it as we work toward https://github.com/bbertucc/equalify/milestone/6

**Comment by bbertucc** [comment]
Re-opening this issue and add @jwgoedert to the issue, since he's going to be creating this component with the add-another pattern as @tvararu referenced.

**Comment by bbertucc** [comment]
This was completed in our yet-to-be-released v1. Closing it here to avoid redundancy.
