### ISSUE TITLE
Send Alerts to Equalify via an API/SDK

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#238]
## What problem is the feature trying to solve?
Equalify currently has no way to log errors via a unit test or a custom behavior-driven test that occurs in an external codebase.

## Desired Solution
Create a simple `add_to_equalify` command to save errors into equalify. Here is an example of how it could work with a simple javascript test:

```
document.getElementById("testButton").addEventListener("mouseover", function() {
    // Get the computed styles for the button on hover
    var backgroundColor = window.getComputedStyle(this, ':hover').backgroundColor;
    var color = window.getComputedStyle(this, ':hover').color;
    
    // Send color contrast errors to Equalify.
    if (contrast >= 4.5) {
       addToEqualify("WCAG 2.1 color contrast requirements met.");
    } else {
        addToEqualify("WCAG 2.1 color contrast requirements NOT met.");
    }
});
```

That's a dumb sample. We could probably add various attributes and make the function name better. Hopefully the dumb sample gets the point across though. 

Once something is logged, it would be saved to the Equalify DB and could appear in a report.

## Alternatives
You could accomplish the same goal by creating a service that worked with Equalify via an integration. That would be difficult to deal with and cumbersome. 

## Technical Details (Optional)
I imagine we would have to create various libraries to import into various different code bases. This might also need to be something that's only added to the cloud version.

**Comment by bbertucc** [comment]
This could take care of #206, since I would imagine it would be easy for devs to write custom tests using Pupetteer and axe that could just leverage this function.

**Comment by bbertucc** [comment]
Also, I think we might consider putting this into the beta version, since we're trying to expand the way content is added to Equalify and this is just one more way to add alerts into the system.

**Comment by TolstoyDotCom** [comment]
On the backend this could use https://github.com/Seldaek/monolog

One possibility is to create hierarchical, semantic logs. For instance, let's say there's code that contacts an API to send three emails. The status of each transmission could be written to the log as an unformatted message. There might be other messages between each of the three messages, the admin would need to grep the log file to see the transmission messages, etc.

Or, the messages could be grouped together under a summary message:
"3 emails attempted, 1 failed"
-- "sent email 'Email 1'"
-- "FAILED email 'Email 2'"
-- "sent email 'Email 3'"

That would be displayed in a tree view. Normally all the emails would succeed so the admin could just skip over those. However, in the case above, the admin would click to open the tree in order to see which email failed.

That could be implemented somewhat like this:

```
function sendEmails() {
	$logKey = 'XYZ' . date();
	$successes = 0;
	foreach ($emails as $email) {
		// the '.1' is for the hierarchy
		$status = $this->sendEmail($email, $logKey . '.1');
		if ($status) {
			$successes++;
		}
	}
	$this->logger('{total} emails attempted, {fails} failed', [
		'logKey' => $logKey,
		'total' => count($emails),
		'fails' => count($emails) - $successes,
	]);
}

function sendEmail($email, $logKey) {
	$status = $externalAPI->sendEmail($email);

	if ($status) {
		$this->logger('email succeeded: {subject}', [
			'logKey' => $logKey,
			'subject' => $email->getSubject(),
		]);
	}
	else {
		$this->logger('email failed: {subject}, error: {error}', [
			'logKey' => $logKey,
			'subject' => $email->getSubject(),
			'error' => $externalAPI->getLastError(),
		]);
	}
}

```
The code that builds the tree view would see 'XYZ123' in one message and three instances of 'XYZ123.1' in others, it'd use that to group them together. It would also notice incomplete things, like two instances of 'XYZ123.1' but no 'XYZ123'. It would flag that something that was possibly interrupted by an exception.

Or, would just basic logging be more appropriate?

**Comment by bbertucc** [comment]
Pretty neat @TolstoyDotCom - We will eventually need some kind of logging tool, but I’m expecting to add that in versions after our December buildout sprint.

I am also going to update this issue title a bit. This issue isn’t about logging errors with the Equalify system. Instead, we would create some sort of way people could interact with Equalify to send alerts from their own codebase. 

I’m not entirely sure of the use case for this feature yet. It was just something I heard in the a11y community. I am going to close this until I hear about specific use cases that would need a feature to send alerts to Equalify.
