### ISSUE TITLE
Refactor Equalify's API

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#283]
## What problem is the feature trying to solve?
Our API was built ad-hoc. It doesn't follow conventional REST standards, so it's not easy to integrate with.

## Desired Solution
A robust RESTful API to do everything Equalify demands.

## Technical Details
A new API would have to handle all the equalify [actions](https://github.com/EqualifyEverything/equalify/tree/main/actions) in addition to what the current [dumb API does](https://github.com/EqualifyEverything/equalify/tree/main/api) does around posting data.

**Comment by alexstine** [comment]
Need to model this after how Octopus Deploy works and other similar tools. Write the rest API and throw a front-end on top of it. I do not have the bandwidth for this level of heavy dev work but like where this could end up. 👍

**Comment by bbertucc** [comment]
> Need to model this after how Octopus Deploy works and other similar tools. Write the rest API and throw a front-end on top of it. I do not have the bandwidth for this level of heavy dev work but like where this could end up. 👍

Love that @alexstine - thanks for the pro tip. Hoping someone jumps on this.

**Comment by beatboxchad** [comment]
I absolutely love this kind of work, but I'm still fussy about how I spend my energy. If I bite, I'll go all-in for the whole month. It's difficult for me to regulate my hyperfocus. As a professional, I need to learn how to harness that energy in a more collaborative way, and I absolutely suck at the negotiation part. My day-to-day personal security (food, medicine, utilities, etc) is spotty enough to impact my judgement and disrupt my ability to take the lead (I've run aground on flat rates too many times).

However I am a very talented engineer with lots of experience and deep passion for the craft, and my values are aligned with a project like this one. I'm leaving this comment to note that I'm following this development and invite anyone who wants to spearhead it to toss me a couple billable hours here and there during April, or just make sure I'm fed and the war machine isn't.

(PS I don't use GPT for writing or creative heavy lifting, only simple repetitive tasks I would otherwise spin out on like "generate a list of unit test names following the Arrange Act Assert pattern from the following class" or "show a command to filter all files not edited by person@example.com out of this git repository". It's a powerful accessibility tool!)

**Comment by bbertucc** [comment]
I'm just doing this as part of #300

**Comment by bbertucc** [comment]
I changed my mind about doing this as part of #300 LOL. Re-opening it and adding @heythisischris onto the project. The proposed work is available [here](https://github.com/EqualifyEverything/equalify/issues/278#issuecomment-2021746829).

I put together a repo for the work here https://github.com/EqualifyEverything/equalify-api

**Comment by bbertucc** [comment]
Closing this since we're moving forward on a different rep
