### ISSUE TITLE
Screen Reader Regression Testing (Version 1 - RC4)

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#287]
We made lots of updates related to screen readers (see #272). We need screen reader users to test those updates.

**Comment by bbertucc** [comment]
@kevinandrews1 can you jump on this? You can report any issues here or as a separate issue in the repo.

**Comment by bbertucc** [comment]
Assigning @kevinandrews1 to this test. He wrote in an email to me:
> Ya, I can absolutely do that!

**Comment by kevinandrews1** [comment]
For context, here's the [results of the screen reader testing](https://docs.google.com/document/d/1n3vLdrdSILtnlPKAgv7Vqoj40NHy_Y2ffXNQprl4fd8/edit?usp=sharing) I did for v1rc3. @bbertucc and I discussed and they said it was okay to just drop the issues from v1rc4 testing here. I'm open to collaboration and all the things/Zoom/screenshare either asynchronous or real-time depending on who's working on this! The stats are basically identical except I think it's now on Chrome 122 something--can get exact number if needed:
-   Still issues with receiving pw reset email. Not sure if it's the email domain (a .edu in this case) or on the Equalify backend somewhere. Can try to help troubleshoot further.
-   Settings/Add Property: This appears in the title of the page: "<br /> <b>Warning</b>: Undefined variable $property_name in <b>/workspace/helpers/get_page_title.php</b> on line <b>45</b><br /> Property Settings | Equalify".
-   Settings/Add Property: The Sitemap URL text field has a note after the label about the requirement for the URL to follow specific schema, but that message isn't programmatically associated with the text field, so tabbing past the text field i.e. the next focusable element you land on the link called "XML Sitemap schema" without the appropriate context.
-   Pressed button Process 20 Scans. Like in V1RC3, after the scans are processed, the screen reader begins reading off the entire list of results in one contiguous chunk. In the case of this testing that was a list of 16. That's overwhelming and way too verbose. I recommend just having some messaging that "x" number of scans completed, provide a semantic heading for the user to easily jump to the results on their accord, and inform of the heading in the message. It so happened I stopped it speaking after the fifth or sixth item and was looking for the results which I assumed would be preceded by a heading. When that wasn't the case, I encountered the button to process 20 scans again. Not a11y per se, but it could be a little misleading for someone if they're not sure that the scan already completed, maybe they missed the alert (stopped the screen reader/was doing something else and missed it, etc).
-   Reports/New Report: Title page is too generic, "Equalify | Accessibility Issue Management".
-   Reports/New Report: After updating the report title the focus still resets. This might be a JAWS issue because that continues to be okay on NVDA and the focus continues (see the note in v1rc3 doc but basically the next tab press moves you in tab order as expected rather than back to the skp link). For example, after the title is updated and the alert fires, pressing tab, expecting to continue progressing through the form, the next tab press is on the skip link and you essentially have to work you way all the way back to the form to pick back up where you left off.
-   Reports/Add Report/Add Filter: The field "search and select filter values" always says "no search results" when the user tabs onto it. A user might think there aren't any results. I recommend a clearer message instructing the user to type and that results will appear they can use the up and down arrow keys.
-   When searching to filter by property, you're told how many results there are but not how to access them. Recommend a quick tip how using the arrow keys/press entr to select.
-   After removing the filter, an alert is spoken that the changes were successful, though there's no change--it needs to be clearer and tell the user the removal, not change, was successful.

**Comment by bbertucc** [comment]
Thanks @kevinandrews1! We'll keep this issue open for a bit to see if anyone else has tests to drop in, then I'll break this down into tasks for our dev team to complete.

**Comment by bbertucc** [comment]
This ticket is kind of redundant because https://github.com/EqualifyEverything/equalify-frontend is overriding all our frontend work. That said, I'm keeping this open until we launch our Version 1 just in case the new frontend doesn't work out.

**Comment by bbertucc** [comment]
Closing this issue, since we're now moving to https://github.com/EqualifyEverything/equalify-frontend
