### ISSUE TITLE
Filter choice of including or excluding

### ISSUE THREAD

**Issue by joelhsmith** [bbertucc/equalify#318]
## What problem is the feature trying to solve?
Filters are only additive. You choose an option and it only shows that, rather than filtering out what you choose.

## Desired Solution
When I choose something to filter out, it filters it out instead. For example, I would like to see a report without `best-practices`.

## How does this feature help fix accessibility issues?
Focusing on clear violations is helpful for prioritization.

## Technical Details (Optional)
Can we make the Filter an opt-in to a Tag or opt-out of a Tag?

**Comment by bbertucc** [comment]
Thanks @joelhsmith! I'm going to transfer this issue to the [equalify-frontend](https://github.com/equalifyEverything/equalify-frontend) repo where issues like this will be logged. 

This might be a Version 1.5 feature since it would require new UX. 

Fathom Analytics has a pretty good solution for what you're talking about. I've attached screenshots. Basically, you can toggle "is" or "is not" for each filter. A live demo is here: https://app.usefathom.com/share/deasaicp/hilarious+platypus?comparison=none

<img width="406" alt="Screenshot of fathom with filter reading IS" src="https://github.com/EqualifyEverything/equalify/assets/46652/3c312454-fc7b-452c-a506-35da477c4b17">
<img width="425" alt="Screenshot of fathom with filter reading IS Not" src="https://github.com/EqualifyEverything/equalify/assets/46652/99d9fd18-c0ad-4288-9422-e33341b2b1ee">

**Comment by bbertucc** [comment]
Going to close this issue so we can focus on V1 issues. That said, filtering like this is super important. Tagging @wilsuriel03 so he sees this and can factor it into mockups for our next version.
