### ISSUE TITLE
Equalify V1 Outreach

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#333]
# Official Equalify Version 1 Outreach Proposal
## Summary
The three-month outreach program will start on June 10 and involves a detailed strategy to engage key stakeholders, demonstrate the product, and secure contracts. To ensure progress, weekly meetings with Blake and asynchronous communication via Slack will be maintained. The goal is to establish Equalify as a viable alternative to more expensive automated accessibility solutions, demonstrating its scalability, robustness, and ease of use.

The objective is to secure contracts with higher education stakeholders, aim for 100,000 pages scanned by September 1, and acquire at least three customers.
## Introduction
Draft of our pitch:

> Introducing Equalify, the ideal and cost-effective solution for higher education institutions committed to digital accessibility. Equalify streamlines the process of making university websites accessible to all students, faculty, and visitors. With its fast, robust, and scalable platform, Equalify scans entire websites using just a sitemap, delivering detailed accessibility reports without requiring advanced technical skills. The included Chrome extension allows users to check and enhance accessibility directly from their browsers. Ensure conformance with today's accessibility standards, improve user experience, and support an inclusive campus environment effortlessly with Equalify. Embrace digital inclusion with Equalify today!
## Budget
Total Budget for Three Months: $6,666
### Payment Structure and Allocation:
- Option 1:
    - 50% Upfront: $3,333 due June 10
    - 50% Contingent: $3,333 upon completion of the project
- Option 2:
    - $2,222/mo invoiced in addition to the other a11y work
### Phase 1: Preparation (June 10 - June 23)
- Tasks:
    - Finalize outreach strategy and materials
    - Set up social media accounts and content plan
    - Identify and reach out to initial contacts within the higher education sector
- Deliverables:
    - Outreach materials (emails, presentations, brochures)
    - Social media profiles and initial content calendar
    - List of initial contacts and stakeholders
- Milestones:
    - Completed outreach strategy
    - Social media presence established
    - Initial contact list finalized
### Phase 2: Engagement (June 24 - July 21)
- Tasks:
    - Launch social media campaign
    - Conduct product demonstrations
    - Engage with higher education community through webinars, listserves, and online events
- Deliverables:
    - Social media posts and engagement metrics
    - Recorded product demonstrations
    - Webinars and event participation records
- Milestones:
    - Social media campaign initiated
    - First round of product demonstrations completed
    - Webinars conducted with higher education stakeholders
### Phase 3: Follow-Up and Conversion (July 22 - August 18)
- Tasks:
    - Follow up with interested stakeholders
    - Provide trial access and support for Equalify
    - Collect feedback and refine the pitch based on responses
- Deliverables:
    - Follow-up emails and communication logs
    - Trial accounts and support documentation
    - Feedback reports, surveys, testimonials, etc
- Milestones:
    - Stakeholder follow-ups completed
    - Trial accounts provided
    - Feedback analyzed and pitch refined
### Phase 4: Contract Negotiation and Finalization (August 19 - September 1)
- Tasks:
    - Negotiate and finalize contracts with interested stakeholders
    - Provide onboarding support for new customers
    - Prepare final outreach report
- Deliverables:
    - Signed contracts
    - Onboarding documentation
    - Final report on outreach initiative
- Milestones:
    - Contracts signed
    - Customers onboarded
    - Outreach report completed
## Key Performance Indicators (KPIs)
- Quantifiable:
    - Number of social media engagements (likes, shares, comments)
    - Number of product demonstrations conducted
    - Number of trial accounts initiated
    - Number of contracts signed
    - Number of pages scanned by September 1 (goal: 100,000 pages)
- Qualitative:
    - Stakeholder feedback on product usefulness and ease of use
    - Customer satisfaction with onboarding and support
    - Impact of Equalify on improving web accessibility in their institutions
    - Engagement quality during webinars and online events
    - Perception of Equalify compared to more expensive alternatives
## Conclusion
This initiative aims to demonstrate the value of an affordable, robust, and scalable accessibility solution to higher education institutions. By strategically engaging stakeholders, showcasing product benefits, garnering and responding to feedback, and providing exceptional support, Equalify will establish itself as a viable alternative to more costly solutions, securing contracts and ensuring sustainability.
## Next Steps
- Finalize outreach proposal and strategy
- Confirm payment arrangement
- Set up and plan social media engagement
- Begin initial contact outreach within the higher education sector

**Comment by bbertucc** [comment]
This is great @kevinandrews1! Can we decide on this during the weekly contributor meeting, Monday?

Do you have any idea of what Social Media communities you'll focus on? I always find it's best to engage with specific communities, in addition to doing just general posts.

You also might want to consider outreach into Slack communities. I know HighEdWeb and a11y are two central areas for folks interested.

**Comment by kevinandrews1** [comment]
Hey @bbertucc, awesome! Discussing at the contributors call next week sounds great. Can I go first on the agenda? I have a hard stop at 12:30 EDT.

For social media, I'm planning to focus on Twitter (now X, though unclear of its a11y since the a11y team got disbanded) and LinkedIn since they have active communities around higher education and accessibility. We're looking to engage specifically with groups like EDUCAUSE, AHEAD, WCET, and the Higher Ed Accessibility taskforce on Slack. This should help us tap into relevant discussions and connect with key stakeholders.

Regarding Slack, absolutely! HighEdWeb and a11y are fantastic suggestions. I'm already a member of some of these communities and so that should help facilitate organic participation in conversations there. It's a great way to directly engage with folks who are passionate about web accessibility.

I do want to chat with you about Equalify on existing platforms and where its presence may already be established, too.

Are you shooting for a democratic process around payment i.e. we discuss during the call and get input from the Equalify contributors? P.s., I like this and think it makes sense - just looking for clarification. I think we can mirror the process you used fpor the [ticket with your job desc](https://github.com/EqualifyEverything/equalify/issues/304).

Looking forward to collaborating!

**Comment by bbertucc** [comment]
That all makes sense @kevinandrews1 

And yes, I'm shooting for a democratic process around payment. 

Happy to make you first on the agenda!

**Comment by bbertucc** [comment]
Since [my tasks](https://github.com/EqualifyEverything/equalify/issues/304) have sales and marketing included in it, I probably should pipe up and add some additional comments, so we can get the most out of our Monday meeting. I’ve divided it into three sections with lists. Point number 8 in the first section is probably the most important. Curious to hear new conclusions you, or anyone else, come to.

## Additional general notes:
1. I’m hopeful but dubious that you’ll find sales. The reason I am dubious is because outreach is a new avenue for you. You haven’t done it before on a big scale. We need to honor that that inexperience so we can work toward success.
1. We should set the expectation that we would be in near daily contact. In my experience, marketing is a discussion. You’re chasing human reaction. And humans are unpredictable. Fluidity is necessary. Most ideas fail. We must work to a system of failing quickly then iterating. Maybe setting a meeting three times a week? They can be short 15 min meetings. At $2222/mo I would expect 60-90 hours of work per month. Wins will translate to more money.
1. Higher Ed Sales Cycles are super slow. I would name you CEO right now if you could grab a bunch of new contracts within three months. I don’t know if that’s possible, but hope to be surprised.
1. Preparation should be done with community involvement. Nothing behind closed doors. We have to use the fact that this is an open source project. That means reaching out to connections and communities to help craft ideas. Be more of a facilitator than a dictator. (The A11y Slack “Freelance” channel has been good for this.) 
1. Who are we reaching out to on June 10? What are we asking them?
1. Ask direct questions. If you want to know how to sell to someone, ask them. I hate propaganda. If someone isn’t interested, we don’t need to waste time with them. It’s a numbers game.
1. Form human connections. The more people get to know us, the more they will want to work with us. How can we do that?
1. I am probably not right. I’m definitely an unccessful sales person. Sure, I have sold millions of dollars of work. That mostly came from doing good work. I am dubious if outreach even leads to anything at all. Maybe we just need to think about ways to share our work vs ways to get sales? I don’t know.

## Equalify Assets
We should remember we already have these assets:
- Friends and past contacts. Everyone I reached out to over the years is fair game. Need to aggregate all these emails into direct marketing and newsletter marketing segments. (Everyone should at least receive a newsletter. Some should be followed up with personally.)
- Our Braintrust. This is a google group. Maybe we get this going angain? Maybe you run it?
- Existing Users. There are over 50 (maybe like 90) users. These folks have used Equalify. We need to start a regular email up updates. Maybe you run that regular email? This is not a marketing newsletter. This is just a way of notifying users what’s updated.
- Social (Twitter and LinkedIn). There are only a handful of folks subscribed to these platforms. Building our ego with large follower counts doesn’t interest me. I would only be interested in building these lists if it led to users + sales.
- Contributors. A bunch of people contributed to Equalify on GitHub. They believe in this project more than anyone.
- The WordPress Community. We’re donating a lot to WordPress. They should be a community that supports us, just like we support them. I need to do a better job of getting community support, though I’ve thought that our impact would speak for itself.

## Some of my past experience:
- Built a Braintrust of Higher Ed pros that meet once a month to review updates. Stayed constantly engaged with that Braintrust. Helped make their ideas a reality by pushing them into GitHub tickets. Followed up with individuals. Engage, engage, engage. They became our biggest cheerleaders and helped us understand our market. Though it didn’t lead to sales, and I stopped it. Too much time. Not enough impact.
- Gave the product away for free. We have over 50 folks signed up to Equalify. Very few of them are actually using it. Maybe we reach out to them

**Comment by kevinandrews1** [comment]
My responses @bbertucc before I'm offline for a couple days in the woods. Really appreciate the realistic take here and definitely needed a reality check!
1. Correct. Haven't done a large marketing/outreach project of this scale. Excited to try (and maybe fail)and learn in the process.
2. That works out to roughly 15-23hrs/week. I am ok committing to that for the next three months unless there are major changes in my life/professional circumstances. Three days a week for 15 minutes makes sense and would help us maintain a good cadence so we can be agile in this process. Would prefer early weekday mornings but am pretty flexible.
3. Fair enough. Yes, probably overoptimistic. Also probably approaching end of fiscal for a lot of schools which may complicate things too. Procurement is tricky in the best of cases at institutions. Maybe one contract is a win or at least a demo for set period of time? Not sure what you think of that or whether that's even something we have the ability to offer right now
4. Absolutely agree and thank you for this reminder.
5. Need to think about this more. Can we discuss and brainstorm further next week?
6. Thumbs-up to that. We should connect with them and find out any challenges they're dealing with and painpoints and it can lead us to ways of maybe integrating Equalify into their workflows.
7. Yeah, you and I are connections people and I think we lean into that. Make this tangible rather than jsut reduce your a11y issues. I want to make it clear it transcends mere compliance. There's real human impact costs and benefits to acting or not acting on a11y of their website(s).
8. Love it. I am also not right and believe humility is probably our greatest asset. I'm open to learning from those who've charted these paths before us as a guide and windows into what works/doesn't.

**Comment by bbertucc** [comment]
Amazing @kevinandrews1! This project has my thumbs up, based on your excitement alone. Excitement and commitment lead to great outcomes (even if it's just a lot of good lessons). Of course, we still need to discuss this with other contributors. If no one has any major problems by the end of the discussion, I'll pay the first $2,222.

**Comment by bbertucc** [comment]
Adding comments from Ray who runs [Bywater Branding](https://bywaterbranding.com):

My initial thoughts on this proposal:
- Take the last sentence from both the Proposal Summary and Introduction to the top of each paragraph.
- I would proceed with Option 2 for payment as this proposal has potential for scope creep and may require different deliverables than originally planned as you proceed with outreach work
- Is brand messaging & visual identity established? CTAs? Taglines? Graphic Components? It is important to launch with a strong voice, look, and feel to instill confidence in this new product. Educational Institutions get pitched solutions often, and move slowly to make a change or investment. If you are able to make contact and gain someone's ear, you want to be prepared to capture their confidence with  brand cohesion and ample trust symbols.
- Phase 1: This seems solid. I would provide more detail on what qualifies the social media presence as "established" and what will be included in the outreach strategy. Make sure to prepare during this time to automate scheduling and create a streamline experience for any interested stakeholders.
- Phase 2: This phase feels like an aggressive timeline. How much time will be spent doing outreach and engagement? Do you anticipate initial meetings prior to booking a demonstration? How many? How long? How will you manage your availability for this array of tasks? I might move product demonstration tasks into phase 3, and focus Phase 2 solely on outreach and preparation for Phase 3. Use phase 2 outreach to  schedule demonstrations for Phase 3 and prepare the onboarding process to be as streamlined as possible to establish credibility from the get go (no multitasking). This way Demonstrations, recordings, follow up, trial access, and feedback collection can all happen together and create a positive experience for early adopters to rave about. Some form of onboarding support should be ready before you make any demonstrations to potential clients, so eager beavers can jump on the bandwagon immediately if they choose.
- Phase 3: It's go time! 
- Phase 4: Are drafted contracts ready?
- KPI's looks good

**Comment by bbertucc** [comment]
## Two Quotes from Peter Thiel’s “Zero to One” Book
> network effects businesses must start with especially small markets. Facebook started with just Harvard students—

> Mark Zuckerberg’s first product was designed to get all his classmates signed up, not to attract all people of Earth.

## How do Peter Thiel and Zuckerberg inspire Equalify’s Radical Revolution?
We’re not doing what Peter Thiel or Mark Zuckerberg did. They created their own revolution. They attracted the people they wanted to hang with (or in Zack’s case lord over). That said, Thiel speaks to a formula we can live into: start your global revolution with the people you know best.

## Who do we know best, and actually want to do business with?

Why not focus on Higher Ed administrators who are super intelligent? They could work for Google or start a revolution, but chose to work at a University. Even if they randomly ended up at their jobs, they decided to stay because they like places of ideas (libraries, coffee shops, chess clubs, ..). These are our people. We like talking with them. Let’s tell them about our revolution, and maybe they’ll want to help us out?

## Why Focus on Radical Higher Ed Administrator Intellectuals?

Everyone who has become a fan of Equalify fits the “intellectual” mold. Equalify is also not something mainstream, so anyone who helps us also has some kind of radical temper.

These Radical Higher Ed Administrator Intellectuals have helped us get wild amazing things done. They’ve gotten us our first contracts, joined our Braintrust, and submitted new ideas constantly. They know how to play University bureaucracy, and believe that that bureaucracy should support new solutions like Equalify. 

I’m particularly thinking of a colleague who came from a hippy-radical family. She’s a homeopath by night and runs a University Center for Latin American Societies by day. Here’s her bio: https://cipr.tulane.edu/person/sefira-fialkoff/. Sefira offered me an office and let me hack on the first version of Equalify. She then preached the gospel of Good Accessibility to her boss, which led to our first dollars. In return, I’m at Sefira’s beckon-call and I’ve been super happy to solve any accessibility bug that comes up.

Folks like Sefira are not just a “target demographic.” They are us. We all share a belief that good things aren’t necessarily born from following every rule. You need to live into intelligence instead of following group thoughts and trends.

## Our Focus is Our Mission

To attract these Radical Higher Ed Administrator Intellectuals we just have to be genuine. We are radically inclined too. We will do what it takes to make the world better. Making the web accessible for people with disabilities is how we make the world better with Equalify. More generally, we believe that equality can be reached by lifting others, not cutting the smartest down. In other words, we are working to a theory of change that elevates everyone to higher intelligence. 

Others like us will help us because they have a theory of change that aligns with ours, and we’re going to use whatever resources we have to make our theory of change happen.

**Comment by bbertucc** [comment]
One thing I just noticed too.. If we started paying $2222 on June 10 and ended September 1, we wouldn't be paying even months of payment. What would the payment for June be, being that work starts 10 days in?

**Comment by kevinandrews1** [comment]
## My thoughts and notes
- Thanks Ray. Scope creep was and is a definite concern of mine. Thank you for voicing it too.
- @bbertucc, apologies in advance if none of this makes sense. I'm often up at weird hours because it's how my brain works, processing crazy ideas and trying to manage the chaos in there at 2AM... We should discuss visual identity, brand cohesion, etc. I'm not a design guy nor would even pretend to be one. Do we have someone/something for that like evena logo as a starting point? That is not I strength I posesse, but happy to discuss ways of ensuring the cohesion and ensuring everyone's aligned.
- Re drafted contracts, we don't have any, I don't think Blake? Do we have a lawyer or know anyone who can create a template and give it a good sniff test? I can do it as a fairly confident armchair lawyer with no law degree but good writing skills and a borderline obsession with attention to detail, but it would take a good chunk of time and don't feel particularly qualified to draft it without review. There's probably something we can use that doesn't require reinventing the wheel.
- For the June payment here's the breakdown. I have a few days I will not be available at all or only partially with some professional commitments and a bike camping trip in a few weeks, and it's only fair I'm transparent about it early on:
    - Unavailable all day June 17
    - Available for a quarter day June 18
    - Available for a quarter day June 21
    - Unavailable all day June 22
    - Available for two-thirds of June 23
- Unavailable days calculation:
  - June 17: 1 day
  - June 18: 0.75 day (unavailable for three-quarters)
  - June 21: 0.75 day (unavailable for three-quarters)
  - June 22: 1 day
  - June 23: 0.33 day (unavailable for one-third)
- Total unavailable days:
    - 1 + 0.75 + 0.75 + 1 + 0.33 = 3.83 days
- Available working days in June:
    - 21 - 3.83 = 17.17 days
- Proportion of the month available:
    - 17.17 days / 30 days ≈ 0.5723
- June's billing amount:
    - $2222 * 0.5723 ≈ $1271.92
- Todo:
    - Think through the loose ends so I can start next week. Also want a shared drive to have a working doc or something to refer to or use Github I'm cool with either.
    - Get green light on billing from Blake and the rest of the community.
    - Establish thrice weekly call cadence with Blake subject to whatever life throws at us but good to at least get something on the calendars.
    - Would be helpful to have an Equalify email if I don't. If you have G Suite even better I can use a calendar to which you and I and everyone else has access to track everything. Wanna keep personal and Equalify separate.
        - Clarifying scope - I'm me in the Unlocked Freedom Access capacity supporting Equalify while putting the human touch on it.
    - Demoing as an sme makes sense. Maybe we get some calls set up with folks and go from there? Probably good to set up a schedule but idk if it should be that rigid. I have a fair bit of ADHD and my neurodivergence kinda necessitates I at least have a path forward with dates even if it's subject to change so I can keep myself on task.
    - Great points on Slack @wilsuriel03. Do we have a plans page? How are we drafting content for that or just something basic?
- Idk, surely I've missed a buncha stuff, but I'm committed to this and someone who will go in 250,000% intensity if I'm excited about a thing. I'll work my ass off and the only thing I do that might annoy people is overcommunicate--sorry in advance! It helps with my workflow and especially with many hands in this collaborative initiative, I'll need feedback as we iterate. Suggestions/comments in Google Docs type stuff are hard with a screen reader, but GH and Slack are great and always open for synchronous chats too!

**Comment by bbertucc** [comment]
@kevinandrews1 -

In response to your items:
- Added branding to this repo. Here's the link: https://github.com/EqualifyEverything/equalify-outreach/tree/main/branding
- Contracts added here: https://github.com/EqualifyEverything/equalify-legal/blob/main/templates/CONTRACT-TEMPLATE.md
- June Payment Processed

**Comment by bbertucc** [comment]
O and feel free to create issues for the to do items or whatever you need to help you. This repo is yours!

**Comment by bbertucc** [comment]
Processed July payment $2222. Hoping for this month we can hit all those Phase 2 items. I guess we didn't establish a social media presence, as per Phase 1 tasks. We will need to establish something to capture leads around our "Equalify Snippets" video series and other outreach activities.

**Comment by kevinandrews1** [comment]
I'll do some brainstorming on this @bbertucc and have a more concrete plan sussed out for us to discuss next week. For the videos, though I'm not super familiar, I'd imagine Youtube provides data and insights for creators about the activity of their channel and their individual content more granularly?

**Comment by bbertucc** [comment]
Youtube doesn't really provide insights like emails of viewers that we would need for leads. We'll have to think about how to get people to our site or social media channel with the video so we can collect contact information.

**Comment by kevinandrews1** [comment]
Yea @bbertucc, wanna think through how we can turn the vids into leads. I've got some ideas and happy to talk about them during the contributors call today and more inn-depth on Wednesday.

**Comment by bbertucc** [comment]
Sounds good @kevinandrews1 !

**Comment by bbertucc** [comment]
@kevinandrews1 are we good to close this and open a new ticket around a UFA partnership and another one on continued a11y support?

As per our conversation, we would focus more of your time on a11y support and come up with a few simple partnerships - like the snippets videos. 

Does that sound good? Happy to discuss more during our sales call.

**Comment by kevinandrews1** [comment]
Sounds great @bbertucc! Do you mind creating those issues? Closing this one.
