### ISSUE TITLE
Commit Dev Routes to Production

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#362]
We need to make sure the dev routes are now on production.

@azdak can you confirm that? You might also need to walk through the updated routes with @heythisischris.

Once they are in production @heythisischris will need to update the routes he is hitting.

**Comment by bbertucc** [comment]
@azdak said he'll do this with #368 by Tuesday.

**Comment by azdak** [comment]
OK @heythisischris @bbertucc, this is ready to push. Updates: 
- there's a dev branch now :stuck_out_tongue_winking_eye:
- I have a waiting commit moving the code for the existing /dev endpoints into the production endpoints.
- Endpoints paths will all be the same as in the docs, now just the prod endpoints live at `scan.equalify.app/[endpoint]` (same as before), and the dev endpoints live at `scan-dev.equalify.app/[endpoint]`. 
 
@heythisischris let me know if you need to do anything or need anything else from me, and when you give the go-ahead I'll pull the trigger on the update to production. (also sorry no PR, just would get sorta complicated since this is all refactoring the branches themselves lol)

**Comment by bbertucc** [comment]
Looks good. Switching the ticket to @heythisischris to wrap up with revised API handling.

**Comment by azdak** [comment]
This has been pushed to live
