### ISSUE TITLE
Reports Not Loading

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#454]
Reports seem to not be loading or load 404 error. Can't access reports via the API or dashboard. This was after our Learn WordPress scan was complete, but a user (Matt Wisdom) who has nothing to do with WordPress reported an issue aswell:

<img width="573" alt="Screenshot of Matt saying that reports aren't working" src="https://github.com/user-attachments/assets/94747e85-5225-4727-a195-b11ff2851df1">

**Comment by heythisischris** [comment]
@bbertucc Alright, we've got reports loading now. This dealt with a lot of issues that I'll explain on today's contributors call:
- Indexes for relationships were not properly set up, now they are, significantly speeding up queries
- Responses were too large (over 6mb for the WordPress scan, which is above the Lambda body response limit). Easy solution was to compress response w/ Gzip beforehand (gets it down to ~500kb).
- We're ommitting the `messageTags` join on expensive queries (think properties with more than 100 URLs, like WordPress). We'll have to optimize the logic for that join, or perform the joins sequentially instead of in "one-shot" like we're currently doing.
