### ISSUE TITLE
Any updates to our budgets?

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#465]
Our three month bounties are expired this month. 

Here are the tickets:

- #396
- #395
- #324
- #304

Some things we loosly discussed was an established equal hourly for everyone instead of flat-rate payment. I like that because it also forces us to work with folks who are equal in talent to us. We did $70 in the past. Also open to just continuing those tickets. 

Some things to consider: 
- We only have about $30,000 in our bank left. 
- If we continue flat-rate payments, we probably should have clear expectations on work load. We had a few occurrences when other work got in the way of Equalify work.

Feel free to add any comments. Aim to discuss this at our next Monday contributor meeting.

**Comment by kevinandrews1** [comment]
@bbertucc Over the past few weeks, I’ve been carefully considering the best way for us to structure payments at Equalify. With our current financial situation—approximately $30,000 left in the bank—we need to make strategic decisions that are both fiscally responsible and aligned with the values we’ve built around fairness and expertise.

One idea I’ve been brainstorming is the possibility of moving toward an equal hourly rate for everyone involved. This approach offers several advantages, primarily in ensuring fairness across the board. Each team member would be compensated based on the time they contribute to the project, which creates a sense of equity and reflects the value of our collective expertise. Additionally, this method offers flexibility, allowing us to scale the amount of work according to our budget while maintaining a high standard of quality.

That being said, there are challenges to consider. Managing and tracking hours could create additional administrative overhead. It’s also possible that limiting hours due to cash flow could slow down our progress. We would need to be diligent in how we allocate hours and prioritize tasks to ensure we are making the most of our resources. However, with careful planning and clear communication, I believe these challenges can be effectively managed.

A key point that I’ve given a lot of thought to is how we approach accessibility work. Historically, we’ve paid a higher hourly rate for accessibility due to the specialized skills required. It’s an essential, niche area that is critical to our mission. While I don’t think accessibility should be an exception to our overall payment structure, I do believe the higher rates for accessibility work are justified because of the expertise involved. That said, I am open to exploring whether we could move to a flat-rate payment model for accessibility as well, provided we account for the specialized nature of the work. The goal here is to ensure fairness and maintain cohesion across the team without causing concerns about disparities in compensation.

On the other hand, continuing with flat-rate payments offers its own set of advantages, particularly in terms of budget predictability. With flat rates, we can forecast costs more easily, giving us greater control over our financial planning. Flat rates also tend to drive efficiency, as they encourage team members to focus on deliverables rather than simply tracking hours.

However, we have experienced some challenges with this model in the past, especially when other obligations have interfered with progress on Equalify. To make this model work, we would need to set clear expectations regarding workloads and ensure accountability so that we stay on track and meet our deadlines without overwhelming anyone.

Ultimately, both models—hourly rates and flat-rate payments—have their merits. An hourly rate ensures fairness and flexibility but may require more oversight and administrative effort. Flat rates provide predictability and drive efficiency but demand clear accountability and well-defined expectations.

There may also be an opportunity for a hybrid model, where we implement hourly rates for more complex or ongoing tasks, such as accessibility work, while maintaining flat rates for smaller, well-defined projects. This would allow us to balance flexibility and predictability in a way that serves both our financial goals and our commitment to high-quality output.

As we move forward, I want to ensure that we find a payment structure that respects the time and expertise of everyone on the team, while also being sustainable for the long term. I’m looking forward to hearing your thoughts as we work toward a solution that benefits both Equalify and its team members.

**Comment by bbertucc** [comment]
Thanks @kevinandrews1!

After today's round of regular payments, we have $24,188.20 in the bank. 

As you highlighted, part of this discussion will be how we prioritize the rest of the budget. Every dollar needs to go to getting more cash. We can do this by building stability, features people want, or invest in sales. If past experience is any lesson, people buy a product when the product is reliable so my gut tells me to put most cash toward sustainability and bank on the two big outreach initiatives we have coming up (CSUN and Educause). But who knows? Curious to hear as many ideas as possible.

**Comment by bbertucc** [comment]
So.. here are a few points on what I'm thinking around budgeting:
- We have $22,698.64 left in our budget (minus $2,500 for #365, $250 for #455, $1,375 for #441, an unspecified amount for #464, $220.85 for advertisement printing, and roughly $250/mo for hosting and Calendly fees)
- CSUN is March 10-14, and I hope we can last with that cash until then. 
- Perhaps we have a common bounty for development and design? "$x" per month until March 30.
- The $x would be decided on between @azdak @heythisischris and @wilsuriel03 
- @azdak would focus on Monitor, Scan, and general full-stack support
- @heythisischris would focus on the API, LLM and general full-stack support
- @wilsuriel03 would develop a roadmap for integrating the V2 frontend and implement that by February 10 (giving us a month of tuning before CSUN) - we would need to make sure you have time @wilsuriel03!
- @alexstine - I would love for you to join the list of folks getting a monthly bounty if there was something you could focus on (maybe even splitting the V2 frontend coding with @wilsuriel03 ?) 
- We pause bounties on new feature development, only tackling new features as we get new clients to pay for them through separate budgets.
- @bbertucc will handle project management for $333 per month.
- @kevinandrews1 will continue to handle managing accessibility for $x - @kevinandrews1 this is up to you - there will hopefully be lots of testing when we implement the V2 design, so maybe it's even the same monthly as the other folks get? You would be in charge of guaranteeing accessibility, so if things aren't accessible it's on you *wink
- Anyone who generates leads for new sales will get 11% of the sale. If we can't say who the lead came from, then we'll just split 11% of the sale evenly between team members. (Anyone is welcome to Educause and CSUN to generate leads.)
- We pause any other spending, focusing all our promotional dollars what we've already bought: CSUN and Educause
- We cap our tech budget at $250/mo
- We continue our Monday contributor meeting, Every other Wednesday Sales meeting, and Thursday technical review meeting - those seem to be working.
- We party in California to celebrate our wild success at CSUN, after we make enough cash to buy The Magic Kingdom? Or at the very least, I know amazing cheap LA burrito trucks and we can stay with my mom in her tiny apartment.

Adding everyone who received a bounty ( @kevinandrews1 @wilsuriel03 @azdak @heythisischris ) + @alexstine who I would love to work with us on some sort of regular basis.

**Comment by alexstine** [comment]
@bbertucc I'm happy to contribute some accessibility fixes but with my limited vision, front-end dev is fairly hard for me. I'll be around for accessibility fixes and any type of infrastructure engineering/architecture needs.

The hourly rate makes more sense because you can pay people for the work they are doing. One of the huge minuses on flat rate for me is I tend to lowball myself on estimates. Then I end up paying the price when the effort is much greater. I do think there should be a separate discussion on how to track these billed hours though. For consultants, it's easier to bill per hour vs. flat rate work as we're offering advice/guidance, not really doing project work. I think $70/hr is very fair especially considering the specialized skills others bring to the table.

That's kind of where I stand... Thanks.

**Comment by bbertucc** [comment]
> One of the huge minuses on flat rate for me is I tend to lowball myself on estimates

@alexstine one of the happy outcomes of Equalify is that most of the people who lowball estimates don't feel screwed (I include myself in this) because there's a longer arc to the project. One lowballed bounty could lead to a payday bounty. Also, people haven't really felt screwed because we're doing morally good work. I like to work with people who want to do good first, and see money as a bonus. That's not to say people shouldn't get paid. It's my goal to make sure people see some value for their work, even with our scant resources.

**Comment by bbertucc** [comment]
We decided to continue our current budgets until October 15, focusing on getting a thing we're aggressively selling by then. Will followup with this issue then.

**Comment by bbertucc** [comment]
Closing this in favor of an update to our handbook: https://github.com/EqualifyEverything/handbook?tab=readme-ov-file#how-are-bounties-budgeted
