### ISSUE TITLE
Meter Scans Per Customer (Needs Discussion)

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#468]
## Overview
@azdak and @heythisischris are going to come up with a plan to do this that would allow us to create all sorts of packages for customers.

Specifically, we were thinking about reaching out to small and medium business, like web agencies, with an exclusive deal to test the waters on smaller packages.

## Bountied
Since this is a bountied issue, Assignees should post an estimate that is then approved as per this note in the handbook: https://github.com/EqualifyEverything/handbook?tab=readme-ov-file#how-are-bounties-budgeted

**Comment by bbertucc** [comment]
@heythisischris can you add an estimate to this?

**Comment by heythisischris** [comment]
@bbertucc I also believe this will take 4-8 hours. Starting with 4 hour estimate. Before beginning however, it might be worth having a discussion on finalizing _what_ exactly the goal of this issue is.

- Are we creating pricing plans? If so, we should agree on several tiers (Starter, Pro, Enterprise)
- Are we charging a certain amount beyond X scans? Maybe $0.05/scan above the baked in quotas?

This might be worth discussing on our Thursday meeting (or earlier).

**Comment by bbertucc** [comment]
Sounds good @heythisischris. Before we approve this we should discuss at our Thursday meeting. I'm going to add a "needs discussion" tag to make sure we call attention to it.
