### ISSUE TITLE
Ability to scan pages behind a username/password login.

### ISSUE THREAD

**Issue by alphex** [bbertucc/equalify#89]
Enhancement Request

Can functionality be built to get past a user login (in my case, specifically, Drupal).

The system should be able to take a username/login for a site, and knowing what sort of site it is (drupal/wordpress, etc) know to go to /user for drupal, and fill out the fields.    To get higher permissions.

A few of my clients are using Drupal (in my use case) to host paid for content behind the login, which means MOST of the sites functionality is behind that login.

MVP features would be 
* Enter a URL to login at:      "/user"
* Provide form element ID's to target for USERNAME and PASSWORD and SUMBMIT.

Ideally, best case.
Tell equalify "this is a drupal site, here's the login info", and the app knows what to do.

**Comment by kreynen** [comment]
I completely understand the need, but please don't do this... or at least not this way. Storing actual authentication credentials directly in this project would really increase the requirements to secure the app and certificates used to encrypt/decrypt the values you would need to pass to Drupal. Even if you managed to stored the credentials with something like https://github.com/lockr/lockr-php, there are too many places this could be exposed during the transactions.

The penalty for not securing that well and/or users who add sites not managing it well could be very, very bad.  Like reputation destroying bad. Even if you were running this type of scan on the test environment of a host like Pantheon, unless you are sanitizing elements like personally identifiable information (PII) in Webform submissions with each clone, you are potentially exposing yourself to a breach with mandatory reporting requirements.

An alternative might be to add this at the integration level. For Pantheon you could use something like `terminus drush <site>.<env> uli --name <user>`. That would return a one time URL, but only if Terminus was able to authenticate on the host running Equalify. In this scenario, because there are so many powerful commands that can be done with Terminus, the onus for securing that integration goes well beyond Equalify.

**Comment by alphex** [comment]
For Drupal, the TERMINUS / DRUSH solution is an even better Idea.

And I 100% agree with your security concerns.

1: I was going to assume (probably too graciously) that my clients would use a fake user account
2: This is impossible to enforce, but on the site owner side, we can enable / disable the user as needed to manually run reports.

...
I guess the TERMINUS approach is best.    Who generates the pantheon machine key then?

**Comment by bbertucc** [comment]
Closing this issue for now.

That said, feel free to open it if a specific use case pops up that needs to be addressed.
